server:
  port: 8771
spring:
  application:
   # name: con-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1010/eureka
    fetch-registry: true #从注册中心拉取注册表
feign:
  hystrix:
    enabled: false   #开启熔断
